[features]
seeds = false
skip-lint = false
[programs.localnet]
program = "FgGSSTdu28FdEGCQ77F5RyvWTRgC4qRGBhsMDH4pu2UW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/madha/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
